[character]
symbol = "âœ"
use_symbol_for_status = true

[git_branch]
symbol = "ğŸŒ± "

[git_status]
conflicted_count.enabled = true
untracked_count.enabled = true
stashed_count.enabled = true
modified_count.enabled = true
renamed_count.enabled = true
deleted_count.enabled = true
show_sync_count = true
staged_count.enabled = true
staged_count.style = "green"

[username]
show_always = true
